client/assets/left-white.svg, client/assets/more-white.svg, client/src/Components/SalesProductDetail/styles.scss, client/src/Components/Shared/Header/index.ts, client/src/Components/Shared/Header/styles.scss, client/src/Components/Shared/ProductBar/index.ts, client/src/Components/Shared/ProductBar/styles.scss
- Header 컴포넌트 상품 상세 페이지 용 디자인 및 요소 구현
- 관련 svg 이미지 두 개 추가 (흰색 left 화살표와 more 버튼)
=> [feature] 상품 상세 페이지 헤더 디자인 적용

client/assets/down-xs.svg, client/src/Components/SalesProductDetail/index.ts, client/src/Components/SalesProductDetail/styles.scss, client/src/Components/Shared/Dropdown/index.ts, client/src/Components/Shared/Dropdown/styles.scss, client/src/Components/Shared/Status/index.ts, client/src/Components/Shared/Status/styles.scss
- 드랍다운 컴포넌트 작성
- props 
- lists: 배열 / 원소는 { text : '옵션이름', isWarning: true/false }
- onclick: 함수 / 클릭 시 등록할 클릭 이벤트 리스너
- offset: 드랍다운 표시 기준점 [ 'left' , 'center' , 'right' ]
- 드랍다운 컴포넌트 테스트를 위해 추가 컴포넌트 작성 및 기존 페이지 구조 변경
- 드랍다운 구현 페이지 : 상품 상세 페이지 (SalesProductDetail)
- 드랍다운 사용 컴포넌트 : Status 컴포넌트
=> [feature] 드랍다운 컴포넌트 클래스 작성

client/src/Components/ChatDetail/index.ts, client/src/Components/ChatList/index.ts, client/src/Components/Shared/ChatBubble/index.ts, client/src/Components/Shared/ChatListItem/index.ts
- 기존 컴포넌트가 단일 템플릿 원칙을 고수하고 있지 못한 점을 발견하여 개선 진행
=> [refactor] ChatListItem / ChatBubble 컴포넌트 단일 템플릿 원칙 준수를 위한 개선

client/assets/add-mint.svg, client/assets/close-mint.svg, client/src/Components/Home/index.ts, client/src/Components/Location/index.ts, client/src/Components/Location/styles.scss, client/src/Components/Shared/LocationButton/index.ts, client/src/Components/Shared/LocationButton/styles.scss, client/src/main.ts
- 위치설정 페이지 기본 마크업 작성
- 위치설정 페이지에서 사용하는 로케이션 버튼 클래스 컴포넌트 기본구조 작성
- 메인페이지 로케이션 이미지 클릭 시 위치설정 페이지로 이동
- 로케이션 버튼 컴포넌트 이벤트 등록해야 합니다 ㅠㅠㅠ 언능 하겠습니다 ㅠㅠ
- 이미지 클릭 시 바로 이동이 아니라 드롭다운으로 표시 후 이동해야 합니다 ㅠㅠㅠ
=> [feature] 위치설정 페이지 기본 마크업 구조 및 컴포넌트 작성

client/src/Components/Category/index.ts, client/src/Components/Home/styles.scss, client/src/Components/Location/styles.scss, client/src/Components/Menu/index.ts, client/src/Components/NewPost/index.ts, client/src/Components/Shared/ChatBubble/styles.scss, client/src/Components/Shared/ChatListItem/styles.scss, client/src/Components/Shared/Header/styles.scss, client/src/Components/Shared/InfoProduct/styles.scss, client/src/Components/Shared/Status/styles.scss, client/src/index.html, client/src/scss/animation.scss, client/src/scss/index.scss
=> [feature] 디자인 및 css 수정

client/src/Components/Auth/styles.scss, client/src/Components/ChatList/index.ts, client/src/Components/Location/styles.scss, client/src/Components/SalesProductDetail/index.ts, client/src/Components/SalesProductDetail/styles.scss, client/src/Components/Shared/ChatBar/index.ts, client/src/Components/Shared/ChatBar/styles.scss, client/src/Components/Shared/ChatListItem/index.ts, client/src/Components/Shared/InfoSaler/styles.scss, client/src/Components/Shared/ProductBar/index.ts, client/src/Components/Shared/ProductBar/styles.scss, client/src/Components/Shared/Status/styles.scss, client/src/scss/index.scss
- 아이폰/갤럭시 화면 추가로 깨지는 스타일링 부분들 수정했습니다.
=> [refactor] 멀티 디바이스 환경 깨지는 스타일링 수정

client/assets/end-off.svg, client/assets/end-on.svg, client/assets/logout.svg, client/src/Components/Auth/styles.scss, client/src/Components/ChatDetail/index.ts, client/src/Components/ChatDetail/styles.scss, client/src/Components/ChatList/index.ts, client/src/Components/SalesProductDetail/index.ts, client/src/Components/SalesProductDetail/styles.scss, client/src/Components/Shared/ChatBar/index.ts, client/src/Components/Shared/ChatBar/styles.scss, client/src/Components/Shared/ChatBubble/styles.scss, client/src/Components/Shared/ChatListItem/index.ts, client/src/Components/Shared/ChatListItem/styles.scss, client/src/Components/Shared/ImgBox/styles.scss, client/src/Components/Shared/InfoProduct/index.ts, client/src/Components/Shared/InfoProduct/styles.scss, client/src/Components/Shared/InfoSaler/index.ts, client/src/Components/Shared/InputPopup/indext.ts, client/src/Components/Shared/InputPopup/styles.scss, client/src/Components/Shared/ProductBar/styles.scss, client/src/Components/Shared/Status/index.ts, client/src/Components/Shared/Status/styles.scss, client/src/Components/Shared/TextInput/index.ts, client/src/Components/Shared/TextInput/styles.scss, client/src/scss/index.scss
- 상품 상세 페이지
- 채팅목록 페이지
- 채팅방 페이지
- 계정 페이지
- 위치설정 페이지
=> [refactor] 기획서 디자인 요구사항 미구현 부분 일부 적용

client/src/Components/ChatDetail/index.ts, client/src/Components/ChatList/index.ts, client/src/Components/SalesProductDetail/index.ts, client/src/Components/Shared/InfoSaler/index.ts, client/src/Components/Shared/InfoSaler/styles.scss, client/src/Components/Shared/InputPopup/indext.ts, client/src/Components/Shared/ProductBar/index.ts, client/src/Components/Shared/Status/index.ts, client/src/Components/Shared/Status/styles.scss
- 라우팅 버그 해결 : 이벤트 중복 문제
- 라우팅은 `setEvent`에 넘기지 않고 `mouted` 에서 등록하도록 수정
- 그 외 미구현 사항 개선
=> [refactor] 상품 상세페이지 및 채팅 라우팅 재설정

client/src/Components/Shared/ImgBox/styles.scss
=> fix: img box gradient 수정

client/src/Components/Auth/Logout.ts, client/src/Components/Auth/Register.ts, client/src/Components/ChatDetail/index.ts
=> [fix] eventListener 수정

client/src/Components/ChatList/index.ts, client/src/Components/Location/index.ts, client/src/Components/Shared/ChatListItem/index.ts
=> [fix] 중복 router 모두 mounted 에서 관리하도록 수정

client/src/Components/Auth/Register.ts, client/src/Components/NewPost/index.ts, client/src/Components/Shared/Button/index.ts, client/src/Components/Shared/Button/styles.scss
=> [bugfix] 회원가입 버그 수정

client/src/Components/Shared/CategoryListItem/index.ts, client/src/Components/Shared/ChatListItem/index.ts, client/src/lib/router.ts
- 매개변수 :id 는 모두 문자열 + 숫자 조합으로 간주
- chat 과 post 부분에 임의의 문자열 / 숫자로 라우팅 테스트 진행
=> [refactor] 동적 라우팅 처리 로직 추가

client/src/Components/NewPost/index.ts, client/src/Components/NewPost/styles.scss, client/src/Components/Shared/Button/index.ts, client/src/Components/Shared/Button/styles.scss, client/src/Components/Shared/CategoryListItem/index.ts, client/src/Components/Shared/Header/styles.scss, client/src/Components/Shared/ImgButton/index.ts
- categoryListItem에서 하트 토글시 컴포넌트 전체 리렌더링으로 인한 사진 깜빡임 해결
- 홈헤더의 드롭다운 버튼 커서 수정
- 파일추가 버튼 accept 속성 추가
- 카테고리 타입 버튼 추가
- 글쓰기 페이지는 아직 에러가 조금 있으니 감안 부탁드립니다.
=> [feature] 버그픽스 및 글쓰기 페이지 추가 구현

client/src/Components/SalesProductDetail/index.ts, client/src/Components/Shared/ImgNavigation.ts, client/src/Components/Shared/ImgNavigation/NavItem.ts, client/src/Components/Shared/ImgNavigation/index.ts, client/src/Components/Shared/ImgNavigation/styles.scss, client/src/lib/router.ts
- 이미지 슬라이더를 위한 클래스 컴포넌트 작성
- 마우스 드래그를 통해 좌/우 이동 (무한이동 가능)
- MutationObserver를 통해 기기 변경 감지 후 기기 크기에 맞게 슬라이드 크기 조정
=> [feature] 이미지 슬라이더 작성

client/src/Components/Auth/Login.ts, client/src/Components/Auth/Logout.ts, client/src/Components/Auth/Register.ts, client/src/Components/Auth/index.ts, client/src/Components/Auth/styles.scss, client/src/Components/Shared/Button/styles.scss, client/src/index.html, client/src/main.ts, client/src/scss/index.scss
- 로그인/회원가입 페이지는 유저가 로그인 되지 않은 상태에서 컴포넌트 단위로 렌더
- 각 페이지 전환은 슬라이드 애니메이션 적용
- 로그아웃 페이지는 유저가 로그인 되어있을 때 렌더
=> [refactor] 로그인/로그아웃/회원가입 페이지 렌더 방식 변경

server/app.ts, server/controllers/CategoryController.ts, server/controllers/LocationController.ts, server/controllers/PostController.ts, server/controllers/UserController.ts, server/database/config.ts, server/database/database.ts, server/database/init.sql, server/package.json, server/quries/category.ts, server/quries/location.ts, server/quries/user.ts, server/routes/auth.ts, server/routes/index.ts, server/routes/main.ts, server/routes/posts.ts, server/routes/users.ts, server/services/CategoryService.ts, server/services/LocationService.ts, server/services/UserService.ts
- 데이터베이스 커넥션 관련 래퍼함수 작성
- 질의수행을 위한 기본 쿼리베이스 구조 작성
- 기존 컨트롤러 / 서비스 구조 변경
- 쿼리 관련 폴더 생성 후 연관된 쿼리별로 정리
- 라우터 구조 재정립
=> [chore] database 및 sql 코드베이스 작성

client/package.json, client/src/Components/Auth/Login.ts, client/src/Components/Auth/Logout.ts, client/src/Components/Auth/Register.ts, client/src/Components/Auth/index.ts, client/src/Components/Category/index.ts, client/src/Components/CategoryResult/index.ts, client/src/Components/ChatDetail/index.ts, client/src/Components/Home/index.ts, client/src/Components/Menu/index.ts, client/src/Components/Menu/styles.scss, client/src/Components/SalesProductDetail/index.ts, client/src/Components/Shared/Button/index.ts, client/src/Components/Shared/Button/styles.scss, client/src/Components/Shared/CategoryListItem/index.ts, client/src/Components/Shared/Header/index.ts, client/src/Components/Shared/Status/index.ts, client/src/lib/util.ts, client/src/scss/index.scss, client/yarn.lock, server/controllers/CategoryController.ts, server/controllers/LocationController.ts, server/controllers/PostController.ts, server/middlewares/authenticate.ts, server/queries/interest.ts, server/queries/location.ts, server/queries/post.ts, server/routes/me.ts, server/services/LocationService.ts, server/services/post/PostInterestService.ts
- 홈화면의 글 목록
- 메뉴화면의 판매목록, 관심목록
- 홈화면 컴포넌트들 버튼 눌렀을 때 생성되도록 수정
- 로그인 로그아웃
- 홈화면 로그인 분기처리
=> [feature] 홈, 메뉴, 카테고리, 결과 페이지 api 연결 완료

server/controllers/PostController.ts, server/queries/post.ts, server/queries/postInterest.ts, server/routes/posts.ts, server/services/post/PostInterestService.ts, server/services/post/PostService.ts
- user login request 에서 해당값으로 id 받아 처리하는 부분만 추가되면 될 거 같습니다...
=> [feature] API 연결에 필요한 데이타베이스 모든 쿼리 기본 구조 작성

client/src/Components/Home/index.ts, client/src/Components/SalesProductDetail/index.ts, client/src/Components/Shared/CategoryListItem/index.ts, client/src/Components/Shared/Header/index.ts, client/src/Components/Shared/IconButton/index.ts, client/src/Components/Shared/IconButton/styles.scss, client/src/Components/Shared/InfoSaler/index.ts, client/src/Components/Shared/ProductBar/index.ts, client/src/Components/Shared/Status/index.ts, client/src/Components/Shared/Status/styles.scss, client/src/lib/util.ts, server/controllers/PostController.ts, server/queries/post.ts, server/routes/posts.ts, server/services/post/PostService.ts
- 상품디테일 가져오는 부분 완료
- 로그인 값에 따라 조건부 렌더링 완료
=> [feature] 포스트 관련 쿼리 및 API 연동 마무리 + 프론트엔드 데이터 연동

client/src/Components/NewPost/index.ts, client/src/Components/UpdatePost/index.ts, server/controllers/PostController.ts
- 버그 픽스 및 기능적으로 미구현된 부분 완료했습니다.
=> [feature] 포스트 수정/삭제 버그 픽스 및 기능 완료

client/src/Components/Home/index.ts, client/src/Components/Location/index.ts, client/src/Components/NewPost/index.ts, client/src/Components/SalesProductDetail/index.ts, client/src/Components/Shared/ChatBadge.ts, client/src/Components/Shared/ChatBadge/ChatBadge.ts, client/src/Components/Shared/ImgNav.ts, client/src/Components/UpdatePost/index.ts, client/src/index.html, client/src/lib/util.ts, client/src/main.ts, client/src/scss/index.scss
- 초기 로딩 시 사용할 로딩 스플래시 기본 베이스 작성
- 추가적인 컴포넌트 단위의 로더(Loader) 작성도 필요할 듯 합니다.
=> [feature] 로딩 splash 제작

client/src/Components/CategoryResult/index.ts, client/src/Components/Home/index.ts, client/src/Components/Shared/Loader/index.ts, client/src/Components/Shared/Loader/styles.scss, client/src/lib/util.ts, server/controllers/PostController.ts, server/queries/post.ts, server/routes/posts.ts, server/services/post/PostService.ts
- 포스트를 10개 단위로 fetching 하도록 infinite scrolling 기능 작성
- 해당 기능은 메인페이지(시작화면)과 카테고리 분류 페이지에만 적용
=> [feature] infinite scrolling 기능 구현

client/src/Components/Category/index.ts, client/src/Components/Category/styles.scss
=> [feature] 카테고리 이미지 수정

client/src/Components/Category/index.ts, client/src/Components/CategoryResult/index.ts, client/src/Components/Home/index.ts, client/src/Components/Shared/CategoryListItem/index.ts, client/src/Components/Shared/InfoProduct/index.ts, client/src/Components/Shared/ProductBar/index.ts, client/src/lib/util.ts, server/queries/post.ts
- 기존 비 로그인 유저의 카테고리 아이디를 가져오지 못하는 문제로 카테고리 탭에서도 모든 포스트를 보여주는 오류 발생
- 해당 오류를 수정했습니다.
=> [bugfix] 카테고리 비 로그인 유저 관련 오류 처리

client/src/Components/ChatDetail/index.ts, client/src/Components/ChatList/index.ts, client/src/Components/Menu/index.ts, client/src/Components/Shared/ChatListItem/index.ts, server/controllers/ChatController.ts, server/queries/chat.ts, server/routes/chat.ts, server/services/ChatService.ts, server/socket.ts
- 새로 채팅 온 채팅방들 배경 흰색으로 변경
- 채팅방에서 다 읽고 나왔는데 unread count 안 사라지는 버그 해결
- 채팅방 하나도 없을 때 새로 생성되는 걸 감지하지 못하는 버그 해결
=> [fix] 채팅 관련 버그 해결

client/src/Components/CategoryResult/index.ts, client/src/Components/ChatList/index.ts, client/src/Components/Home/index.ts, client/src/Components/Menu/index.ts, client/src/Components/Shared/CategoryListItem/index.ts, server/controllers/ChatController.ts, server/controllers/PostController.ts, server/queries/post.ts, server/services/ChatService.ts, server/socket.ts
=> [bugfix] loading error 개선

client/src/Components/UpdatePost/index.ts, server/controllers/PostController.ts
=> [bufgix] post 작성/수정 시 가격 입력 오류 수정
